-- Create student registry table used during sign up / log in
CREATE TABLE IF NOT EXISTS public.student_registry (
  college_id TEXT PRIMARY KEY,
  full_name TEXT NOT NULL,
  college TEXT NOT NULL,
  major TEXT,
  year TEXT,
  avatar_url TEXT
);

ALTER TABLE public.student_registry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Student registry is readable for auth flows." ON public.student_registry
  FOR SELECT USING (true);

-- Create a profiles table
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  github_username TEXT,
  skill_fingerprint JSONB, -- Stores the radar chart data
  ai_personality TEXT, -- Gemini-generated personality summary
  dimension_scores JSONB, -- Velocity, Quality, Collaboration, etc.
  bio TEXT,
  college TEXT,
  branch TEXT,
  year_of_study TEXT,
  is_discoverable BOOLEAN DEFAULT TRUE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

-- Backfill columns if table already existed without them
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS branch TEXT,
  ADD COLUMN IF NOT EXISTS year_of_study TEXT,
  ADD COLUMN IF NOT EXISTS repo_audits JSONB,   -- Per-repo Gemini deep audit results
  ADD COLUMN IF NOT EXISTS all_skills JSONB,    -- Cross-repo aggregated skill list
  ADD COLUMN IF NOT EXISTS engineer_type TEXT,  -- AI-categorized engineering role
  ADD COLUMN IF NOT EXISTS strongest_signal TEXT; -- The single most impressive thing detected

-- Verified Skills table for cross-repo aggregation
CREATE TABLE IF NOT EXISTS public.skills (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  student_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'claimed', -- claimed, demonstrated, verified
  repo_count INTEGER DEFAULT 1,
  evidence_strength TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Students table (extended profile for granular identity)
CREATE TABLE IF NOT EXISTS public.students (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  github_username TEXT,
  github_access_token TEXT, -- Optional: store encrypted or if needed for background jobs
  fingerprint_data JSONB,   -- Stores the full analyzeAllRepos result
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view all skills." ON public.skills FOR SELECT USING (true);
CREATE POLICY "Users can manage their own skills." ON public.skills
  FOR ALL USING (auth.uid() = student_id);

CREATE POLICY "Users can view student profiles." ON public.students FOR SELECT USING (true);

CREATE POLICY "Users can insert their own student profile." ON public.students
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own student profile." ON public.students
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile." ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, github_username, username)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url',
    new.raw_user_meta_data->>'user_name',
    new.raw_user_meta_data->>'user_name'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the function on signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Create saved_candidates table for discovery model
CREATE TABLE public.saved_candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id UUID REFERENCES auth.users ON DELETE CASCADE,
  student_id UUID REFERENCES public.profiles ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(company_id, student_id)
);

ALTER TABLE public.saved_candidates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Companies can view their own saved candidates." ON public.saved_candidates
  FOR SELECT USING (auth.uid() = company_id);

CREATE POLICY "Companies can save candidates." ON public.saved_candidates
  FOR INSERT WITH CHECK (auth.uid() = company_id);

CREATE POLICY "Companies can unsave candidates." ON public.saved_candidates
  FOR DELETE USING (auth.uid() = company_id);

